run_name: FM_source
run_folder: FlowMatching
device: 'cuda:7'

method: GenerativeUnfolding
process_params:
  train_slice: [0., 0.8]
  val_slice: [0.8, 0.85]
  test_slice: [0.85, 1.0]
  training_file: "data/Pythia26_full.npz"
  analysis_file: "data/Herwig_full.npz"

# Preprocessing
hard_preprocessing:
  #type: 
  unit_hypercube: False
  args:
    pt_conserved: True
#reco_preprocessing:
  #type:

# Training
lr: 1.e-3
batch_size: 128
batch_size_sample: 10000
lr_scheduler: cosine_annealing
weight_decay: 0.
betas: [0.9, 0.99]
epochs: 30

# Architecture
model: FlowMatching
bayesian: False

latent_space: gaussian
uniform_channels: [4]
uniform_bounds: [0., 1.]
minimum_noise_scale: 0
t_noise_scale: 0


dropout: 0.0
dim_embedding: 16
n_head: 2
n_encoder_layers: 2
n_decoder_layers: 2
dim_feedforward: 32
embedding_nets: False

network_params:
  internal_size: 76
  layers_per_block: 4
  activation: SiLU

  embed_t: True
  embed_t_mode: sinusoidal
  embed_t_dim: 16

evaluate_train: False
evaluate_analysis: False
